## Importing the libraries 

We will import the necessary libraries here

In [ ]:
import numpy as np 
from sklearn.metrics import accuracy_score

## Initialize the hyperparameters 

We will select some basic hyperparameters like number of iterations, learning rate (for gradient ascent) etc

In [ ]:
num_iterations = 20
learning_rate  = 0.2

## Problem statement
We will initialize variables for our problem statement (ie., X and Y) 

In [ ]:
X = np.array([[1,0,1],[1,1,1],[0,1,1],[0,0,1]])

print('The actual input matrix X for OR-Gate is given as')
print(X)

y = np.array([[1],[1],[1],[-1]])

print('The target vector is')
print(y)


The actual input matrix X for OR-Gate is given as
[[1 0 1]
 [1 1 1]
 [0 1 1]
 [0 0 1]]
The target vector is
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [ ]:
def misclassification(true,pred):
  '''
    Finds out the number of observations misclassified by our model 
  '''
  return 1-accuracy_score(true,pred)

## Performing gradient ascent 

We perform gradient ascent to update the weights. 

In [ ]:
w = np.array([[1],[1],[-3]])

for i in range(num_iterations):

  outputs = X@w

  outputs = np.array([1 if z>0 else -1 for z in outputs])

  print('iteration ',i+1,'misclassification rate = ',misclassification(y,outputs))
  print('Predicted results ',outputs.ravel())
  print('Actual results    ',y.ravel())
  print("y(X.w)            ",(y*(X@w)).ravel())
  print("y.T.(X.w)         ",(y.T.dot(X@w)).ravel())

  if misclassification(y,outputs)==0:
    print(f'0 misclassifications attained and the final weights are {w} \n')  
    break

  print("Old value of w   ",w.ravel())  
  
  w = w+learning_rate*(X.T@y)
  
  print("New value of w   ",w.ravel())  
  print('\n')

iteration  1 misclassification rate =  0.75
Predicted results  [-1 -1 -1 -1]
Actual results     [ 1  1  1 -1]
y(X.w)             [-2 -1 -2  3]
y.T.(X.w)          [-2]
Old value of w    [ 1  1 -3]
New value of w    [ 1.4  1.4 -2.6]


iteration  2 misclassification rate =  0.5
Predicted results  [-1  1 -1 -1]
Actual results     [ 1  1  1 -1]
y(X.w)             [-1.2  0.2 -1.2  2.6]
y.T.(X.w)          [0.4]
Old value of w    [ 1.4  1.4 -2.6]
New value of w    [ 1.8  1.8 -2.2]


iteration  3 misclassification rate =  0.5
Predicted results  [-1  1 -1 -1]
Actual results     [ 1  1  1 -1]
y(X.w)             [-0.4  1.4 -0.4  2.2]
y.T.(X.w)          [2.8]
Old value of w    [ 1.8  1.8 -2.2]
New value of w    [ 2.2  2.2 -1.8]


iteration  4 misclassification rate =  0.0
Predicted results  [ 1  1  1 -1]
Actual results     [ 1  1  1 -1]
y(X.w)             [0.4 2.6 0.4 1.8]
y.T.(X.w)          [5.2]
0 misclassifications attained and the final weights are [[ 2.2]
 [ 2.2]
 [-1.8]] 

